### ISSUE TITLE
Failed to read the 'localStorage' property from 'Window'

### ISSUE THREAD

**Issue by stephenway** [songlibo/pagespeed-chrome-extension#26]
Mac OS Version 10.12.3
Chrome Version 57.0.2987.133 (Official Build) (64-bit)

On first run, got:
```
An embedded page at lanlbpjbalfkflkhegagflkgcfklnbnh says:

Error in Page Speed panel:
 Error: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at Object.onDomComplete (chrome-extension://lanlbpjbalfkflkhegagflkgcfklnbnh/pagespeed.js:727:27)
    at pagespeed.DomCollector.<anonymous> (chrome-extension://lanlbpjbalfkflkhegagflkgcfklnbnh/pagespeed.js:706:19)
    at pagespeed.DomCollector.clientCallback_ (chrome-extension://lanlbpjbalfkflkhegagflkgcfklnbnh/pagespeed.js:88:21)
    at pagespeed.DomCollector.onDomCollected_ (chrome-extension://lanlbpjbalfkflkhegagflkgcfklnbnh/pagespeed.js:1047:10)
    at chrome-extension://lanlbpjbalfkflkhegagflkgcfklnbnh/pagespeed.js:1037:13
    at chrome-extension://lanlbpjbalfkflkhegagflkgcfklnbnh/pagespeed.js:88:21
    at callbackWrapper (<anonymous>:60:1)
    at ExtensionServerClient._onCallback (<anonymous>:73:649)
    at ExtensionServerClient._onMessage (<anonymous>:74:9)
```

**Comment by songlibo** [comment]
A fix is coming.

**Comment by songlibo** [comment]
Fixed.
